### PR TITLE
Import iotjs-async to iotjs-modules

### PR DESCRIPTION
**Pull request by rzr**
IoT.js-Modules-DCO-1.0-Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by yichoi** [comment]
please, in order to make sure, squash commits by yourself

**Comment by rzr** [comment]
in iotjs-async ?

**Comment by rzr** [comment]
in iotjs-async ?

**Comment by daeyeon** [comment]
- For the matter, `git commit --amend --verbose` and `force-pushing your PRed commit` won't make any noise. 
- The custom property is missing in package.json.

**Pull request merged**
