### PR TITLE
Add the new url module and the test file for it

### PR DESCRIPTION
**Pull request by pmarkee**
Based on https://github.com/Samsung/iotjs/pull/1528

IoT.js-DCO-1.0-Signed-off-by: Peter Marki marpeter@inf.u-szeged.hu

### CODE REVIEW

**Comment by pmarkee** [comment]
Hi @rzr
Yes, I was asked to submit this here.
https://github.com/Samsung/iotjs/pull/1528#issuecomment-375184630

**Comment by rzr** [comment]
OK, interesting, so I guess a new module should be created to add extra API and makes iotjs minimal....

Actually I am facing a similar situation with I2C module, I will send a PR to check if we can align on similar strategy.

Meanwhile please check:
https://github.com/Samsung/iotjs-modules/pull/2


cc: @daeyeon

**Comment by rzr** [comment]
So the question is should url be a submodule or commited in tree? I have no objection for not using gitmodule for new projects, but I would be nice to have them in the same hierarchy (ie: url.js => url/index.js )  test should be relocated too.

You can see the structure I had in mind at:
https://github.com/rzr/iotjs_modules

I will send a couple of new modules once merged.

**Comment by daeyeon** [comment]
[README](https://github.com/Samsung/iotjs-modules/blob/master/README.md), the guide, has been published after this commit. Sorry for the inconvenience. According to https://github.com/Samsung/iotjs/issues/1441, modules should be registered as a git submodule. Please update your commit.

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
